### ISSUE TITLE
Panning is not reset when running screen order

### ISSUE THREAD

**Issue by ingmarlehmann** [symmsaur/screenorder#1]
When moving from a multi-monitor setup that uses panning to working locally on a laptop screen, panning is not reset (the screen surface is scrollable and oversized).

**Comment by symmsaur** [comment]
Issue fixed by 97c05854032180fcb14d211a8d54fcbe9b720482. @ingmarlehmann Can you retest?

**Comment by ingmarlehmann** [comment]
Fixed!
